//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quastion
    {
        public Quastion()
        {
            this.Variants = new HashSet<Variant>();
        }
    
        public System.Guid QuastionId { get; set; }
        public string Text { get; set; }
        public System.Guid Test_TestId { get; set; }
    
        public virtual ICollection<Variant> Variants { get; set; }
        public virtual Test Test { get; set; }
    }
}
