//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public System.Guid RequestId { get; set; }
        public string Message { get; set; }
        public System.Guid aspnet_Roles_RoleId { get; set; }
        public System.Guid aspnet_Users_UserId { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
