//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSet
    {
        public TestSet()
        {
            this.Quastions = new HashSet<Quastion>();
            this.Groups = new HashSet<Group>();
        }
    
        public System.Guid TestId { get; set; }
        public string Name { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Quastion> Quastions { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
