//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public System.Guid VariantId { get; set; }
        public string Text { get; set; }
        public bool IsValid { get; set; }
        public System.Guid Quastion_QuastionId { get; set; }
    
        public virtual Quastion Quastion { get; set; }
    }
}
